package com.usdataproject.util.helper;

public class InstitutionDataStaticValues {

	public static enum InstitutionDataColumnEnum {
		STNAME, CERT, DOCKET, ACTIVE, ADDRESS, ASSET, BKCLASS, CHANGEC1, CHANGEC2, CHANGEC3, CHANGEC4, CHANGEC5, CHARTER, CHRTAGNT, CONSERVE, CITY, CLCODE, CMSA_NO, CMSA, COUNTY, DATEUPDT, DENOVO, DEP, EFFDATE, ENDEFYMD, EQ, ESTYMD, FDICDBS, FDICREGN, FDICSUPV, FED, FED_RSSD, FEDCHRTR, FLDOFF, IBA, INACTIVE, INSAGNT1, INSAGNT2, INSDATE, INSTCRCD, INSBIF, INSCOML, INSDIF, INSFDIC, INSSAIF, INSSAVE, MSA_NO, MSA, NAME, NEWCERT, OAKAR, OTSDIST, OTSREGNM, PROCDATE, QBPRCOML, REGAGNT, REPDTE, RISDATE, STCHRTR, ROA, ROAQ, ROE
	}
}
